version: '3.9'

services:
  drupal:
    image: drupal:8.2
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    depends_on:
      - postgres
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  postgres:
    image: postgres:14.3
    ports:
      - "5432:5432"
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_USER_FILE: /run/secrets/psql_username
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_password
    volumes:
      - drupal-data:/var/lib/postgresql/data
    secrets:
      - psql_username
      - psql_password
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-data:

secrets:
  psql_username:
    external: true
  psql_password:
    external: true
